export const ActionTypes = {
     UPDATE_USER: "UPDATE_USER",
     GET_USER: ' GET_USER',
    GET_USERS: 'GET_USERS',
     ADD_USER: ' ADD_USER',
    DELETE_USER: ' DELETE_USER',
    LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
    LOAD_USERS_ERROR: 'LOAD_USERS_ERROR',
    IMAGE_USER_CREATE: 'IMAGE_USER_CREATE',
    IMAGE_USER_EDIT: 'IMAGE_USER_EDIT',
    IMAGE_USER_UPDATE: 'IMAGE_USER_UPDATE'
};