export const userConstants = {
   
    UPDATEADMIN_REQUEST: "USERS_UPDATEADMIN_REQUEST",
    UPDATEADMIN_SUCCESS: "USERS_UPDATEADMIN_SUCCESS",
    UPDATEADMIN_FAILURE: "USERS_UPDATEADMIN_FAILURE",
  };